### ISSUE TITLE
About different size feature (extract_features) with ["all"]

### ISSUE THREAD

**Issue by HymEric** [PyRetri/PyRetri#19]
In ```config``` file, I want to use ```all``` features as the image descriptors:
```
extractor:
    name: "MoCoResSeries"  # name of the extractor.
    MoCoResSeries:
      extract_features: ["all"]  # name of the output feature map. If it is ["all"], then all available features will be output.
```
But if the middle feature is [N1,C1,H1,W1], [N2,C2,H2,W2] and the last feature is [N, L]. How to deal with this problem? And in the indexing phase, what about ```feature_names```? is ["all_GEM"] if aggregators=GeM
